# This is a basic workflow that is manually triggered

name: Publish Storybook to GitHub pages

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Publish Storybook to GitHub Pages
      run: npm run publish:gh-pages
